### PR TITLE
Reduce number of callbacks when checking access flags.

### PR DESCRIPTION
**Pull request by dkocher**
Fix for #88.

### CODE REVIEW

**Comment by kofemann** [comment]
ok to test

**Comment by kofemann** [comment]
Please add **Signed-off-by** in to the commit.

**Comment by kofemann** [comment]
retest this please

**Comment by dkocher** [comment]
Not sure what the difference is but the test passes here.

**Comment by kofemann** [comment]
@dkocher This is not the issue of your patch, however, can you add the following:


```
diff --git a/core/src/test/java/org/dcache/nfs/vfs/PseudoFsTest.java b/core/src/test/java/org/dcache/nfs/vfs/PseudoFsTest.java
index 671a608f..cf252ebd 100644
--- a/core/src/test/java/org/dcache/nfs/vfs/PseudoFsTest.java
+++ b/core/src/test/java/org/dcache/nfs/vfs/PseudoFsTest.java
@@ -19,11 +19,14 @@
  */
 package org.dcache.nfs.vfs;
 
+import com.google.common.primitives.Longs;
+
 import java.io.IOException;
 import java.net.InetSocketAddress;
 import java.nio.charset.StandardCharsets;
 import java.util.stream.Stream;
 import javax.security.auth.Subject;
+
 import org.dcache.auth.Subjects;
 import org.dcache.nfs.ExportFile;
 import org.dcache.nfs.FsExport;
@@ -383,7 +386,7 @@ public class PseudoFsTest {
         Inode inode = new Inode(
                 new FileHandle.FileHandleBuilder()
                     .setExportIdx(1)
-                    .build(new byte[] {0x1})
+                    .build(Longs.toByteArray(1L))
             );
 
         given(mockedExportFile.getExport(1, localAddress.getAddress())).willReturn(null);
```

**Comment by kofemann** [comment]
Thanks!

**Pull request merged**
